# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KeKe's blog
email: sxsdjkk@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello world!
  I am a iOS developer from China,
  Contact me via email if you are intetested.
baseurl: “blog” # the subpath of your site, e.g. /blog
url: "ikeke.win” # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  sxsdjkk

# Build settings
markdown: kramdown
